name: tap_water_tab_bar
description: Highly customizable tabBar and tabBarController for Flutter
version: 0.0.1
author: iTeaTime(技术清谈) <luohanchenyilong@163.com>
homepage: https://github.com/iteatimeteam/tap_water

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  meta: ">=1.1.1 <2.0.0"
  redux: ">=3.0.0 <4.0.0"
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - resources/images/account/account_highlight@2x.png
   - resources/images/account/account_normal@2x.png
   - resources/images/fishpond/fishpond_highlight@2x.png
   - resources/images/fishpond/fishpond_normal@2x.png
   - resources/images/home/home_normal@2x.png
   - resources/images/home/home_highlight@2x.png
   - resources/images/lottie_placeholder/gray_tabbar_home_animation_lottie_placeholder@2x.png
   - resources/images/lottie_placeholder/gray_tabbar_me_animation_lottie_placeholder@2x.png
   - resources/images/lottie_placeholder/gray_tabbar_message_animation_lottie_placeholder@2x.png
   - resources/images/message/message_highlight@2x.png
   - resources/images/message/message_normal@2x.png
   - resources/images/post/post_highlight@2x.png
   - resources/images/post/post_normal@2x.png
   - resources/images/home_select_cover@2x.png
   - resources/images/tabbar_background@2x.png
   - resources/images/TabBar_Bg_Shadow@2x.png
   - resources/images/tabbarBg@2x.png
   - resources/images/tapbar_top_line@2x.png
   - resources/images/videoback@2x.png
     